### ISSUE TITLE
TASK #1 : things to study.

### ISSUE THREAD

**Issue by claudiajkang** [ClaudiaJKang/EOF#1]
**[TODO 1 List]**
- [x] 0. 공유 라이브러리 이용해서 프로그래밍 해보기 | [reference](https://www.joinc.co.kr/w/Site/C/Documents/Make_Library) 
- [x] 1. PLT / GOT 구조 알기 | [reference1](https://bpsecblog.wordpress.com/2016/03/07/about_got_plt_1/) | [reference2](https://bpsecblog.wordpress.com/2016/03/09/about_got_plt_2)
- [x] 2. ELF 포멧 숙지하기 | [reference](https://www.dropbox.com/s/f8ikkl6kocyhsfx/elf.pdf?dl=1&pl=1) 
- [x] 3. Internal 문서 보기 | [reference](https://www.dropbox.com/s/fyz7q2onl7ea422/uftrace_internals.pdf?dl=1) 
- [x] 4. Uftrace Project Structure 분석

**Comment by ClaudiaJKang** [comment]
- [ ] 0. 공유 라이브러리 이용해서 프로그래밍 맛보기 
   - [gcc --static opt](https://nicewoong.github.io/development/2018/02/24/c-library-gcc-compile/)
